### ISSUE TITLE
Failed to write message to NFC tag

### ISSUE THREAD

**Issue by dalbir** [don/phonegap-nfc-issue-247#1]
I have used this code but its shows me the Alert "Error Failed to write message to NFC tag".

I want to read my NFC tag.

Mobile Android 4.2

**Comment by dalbir** [comment]
After Commenting the addNdefFormatableListener Android call addTagDiscoveredListener but it not showing HEX Code. It Shws ID with some negative number.

**Comment by don** [comment]
@dalbir this project was created to debug an issue with reading NFC tags

See the main project https://github.com/chariotsolutions/phonegap-nfc for more info
There's an example app for writing NFC tags https://github.com/don/phonegap-nfc-writer
